### ISSUE TITLE
Usage docs

### ISSUE THREAD

**Issue by Arkoniak** [lukemerrick/IEXTools.jl#9]
Thank you for the package, it looks like it provides an access to a useful data. Unfortunately, I wasn't able to figure out how to use it properly.

I tried the following:

```julia
using InvestorsExchange
res = query_hist_filenames()["20210420"][1]

filename = download_file(res["link"], "/tmp/1")
report = read_trade_report_messages(filename)
```

But for some reason, `report` was empty.
```julia
julia> report
InvestorsExchange.TradeReportMessage[]
```
So, I guess, I miss something obvious.

My version of the package is `0.1.0`
```julia
pkg> st
      Status `~/Projects/BabySteps/Discourse/discourse2021-04-21/Project.toml`
  [0f939db3] InvestorsExchange v0.1.0
```

**Comment by lukemerrick** [comment]
Doesn't look like you're missing anything obvious. You're missing something that might help you work around the issue, but that would only be obvious if I had properly documented this code (with time and usage I hope I'll get there).

Basically, assuming the API call to get the download links returns things in the same order for you, the first result is the DEEP feed, not the TOPS feed.

```julia
hist_names["20210420"]
2-element Vector{Any}:
 Dict{String, Any}("protocol" => "IEXTP1", "feed" => "DEEP", "link" => "https://www.googleapis.com/download/storage/v1/b/iex/o/data%2Ffeeds%2F20210420%2F20210420_IEXTP1_DEEP1.0.pcap.gz?generation=1618964309425193&alt=media", "date" => "20210420", "version" => "1.0", "size" => "2727751406")
 Dict{String, Any}("protocol" => "IEXTP1", "feed" => "TOPS", "link" => "https://www.googleapis.com/download/storage/v1/b/iex/o/data%2Ffeeds%2F20210420%2F20210420_IEXTP1_TOPS1.6.pcap.gz?generation=1618965083561660&alt=media", "date" => "20210420", "version" => "1.6", "size" => "2320528751")
```

I've only been working with the TOPS v1.6 feed personally, and it might be there is some incompatibility between my code and the DEEP feed. The thing you're possibly missing is that since I've only implemented the trade record message type, and the TOPS feed contains all the trade messages, there is little reason to mess with the DEEP feed. It's not hard to implement other message types and add them to this codebase, but until you or I or someone else wants them, the TOPS feed has all the data this codebase can read and tends to have smaller files. You can see [IEX's documentation](https://iextrading.com/trading/market-data/) for details on the feeds, btw.

Now, as to why you're getting empty results on the DEEP feed, I'll have to test this out. I'm currently downloading the file you indicated over my not-meant-for-2GB-market-data-files-speed internet connection and will update this thread if I figure out what's up.

**Comment by lukemerrick** [comment]
Update (actually it only took about 10min to download the file): I found what's up. Contrary to what the documentation might suggest, I actually hard-coded the TOPS v1.6 header into the `read_trade_report_messages` function. I had meant to make the feed header (which has some unique magic bytes) a keyword argument, but in the end I forgot, haha :sweat_smile: 

Basically for v0.1.0 you need to use the TOPS v1.6 feed, but that's actually probably a good thing, because if you're trying to read trade report messages, TOPS will have all the same trade report messages as DEEP, and it will have fewer other messages to download and skip through.

**Comment by lukemerrick** [comment]
Fixed with [v0.1.1](https://github.com/lukemerrick/InvestorsExchange.jl/tree/v0.1.1)

(Note in the below example I'm using the Julia 1.6 `import InvestorsExchange as IEX`)

![image](https://user-images.githubusercontent.com/8729935/115737570-1c6c6680-a341-11eb-9c82-49f12da38273.png)

**Comment by lukemerrick** [comment]
(but still, use the TOPS feed for trade messages because it should parse faster due to having fewer messages and should also download a bit faster, too)

**Comment by Arkoniak** [comment]
Thank you!
